### ISSUE TITLE
Guidance on usage

### ISSUE THREAD

**Issue by keirk** [parshap/node-libs-react-native#1]
Hi, Thanks for publishing this package.  I wondered if you might be able to share some additional usage details? I'm trying to get a package working in React Native that is packaged using webpack and thus uses node-libs-browser / buffer. Appreciate any help you can give.

**Comment by parshap** [comment]
I've added some more information to the readme. Basically you want to use the `rn-cli.config.js`. Check out the readme and [this post](https://gist.github.com/parshap/e3063d9bf6058041b34b26b7166fd6bd) for more information.
