### ISSUE TITLE
undefined is not an object (evaluating 'RNRandomBytes.seed')

### ISSUE THREAD

**Issue by ka-sh** [parshap/node-libs-react-native#10]
When using Crypto I get this error. I know it is related to how we should install react-natice crypto but I am not sure why would I need to follow the same instructions there, any ideas ?

**Comment by parshap** [comment]
I think you'll need to follow the instructions here: https://github.com/tradle/react-native-crypto

Namely the `react-native link` step.

**Comment by ka-sh** [comment]
@parshap Thanks for response, I guess I need to have some sort of a work around since our developers are using exp. Will close this since it is more related to installation of react-native-crypto.

Thanks
