### ISSUE TITLE
net module not found

### ISSUE THREAD

**Issue by elios264** [parshap/node-libs-react-native#11]
Hi,

I'm trying to use the Joi module, but it can't find the `net `module.

![capture](https://user-images.githubusercontent.com/15863852/44735292-a5a83e00-aab1-11e8-8fc4-ceaaf52ea122.PNG)

I'm not really sure what's wrong.

it is resolving successfully other requires like `assert` though

**Comment by elios264** [comment]
oh I got it, need to manually replace the null for the mock

**Comment by SuryaChandrasekaran** [comment]
> oh I got it, need to manually replace the null for the mock

Hey, can you explain me how did you fix this issue. I am having the same problem. The 'net' module is not supported by react-native. How do I redirect the require('net') to point to the mock net.js file.

**Comment by parshap** [comment]
See my comment here https://github.com/parshap/node-libs-react-native/issues/18#issuecomment-500146357
