### ISSUE TITLE
Fix: extraNodeModules -> resolver.extraNodeModules

### ISSUE THREAD

**Issue by jdanbrown** [parshap/node-libs-react-native#14]
Not sure when this changed, but to avoid this error:
```
error: bundling failed: Error: Unable to resolve module `path` from `.../index.js`: Module `path` does not exist in the Haste module map
```

I had to change this example of `extraNodeModules` from the README:
```js
// rn-cli.config.js
module.exports = {
  extraNodeModules: require('node-libs-react-native'),
};
```

to be `resolver.extraNodeModules`:
```js
// rn-cli.config.js
module.exports = {
  resolver: {
    extraNodeModules: require('node-libs-react-native'),
  },
};
```

as per the latest metro docs:
- https://github.com/facebook/metro/blob/v0.48.1/docs/Configuration.md

**Comment by parshap** [comment]
Yes, this changed in the bundler at some point. Would you be interested in sending a PR to make this change?

**Comment by jdanbrown** [comment]
👍https://github.com/parshap/node-libs-react-native/pull/16
