### ISSUE TITLE
Module 'net'  cannot be imported. Can someone tell me a fix for this. 

### ISSUE THREAD

**Issue by SuryaChandrasekaran** [parshap/node-libs-react-native#18]
.The error stack trace, for the error is
-----------
The package at "node_modules\tough-cookie\lib\cookie.js" attempted to import the Node standard library module "net". It failed because React Native does not
include the Node standard library. Read more at https://docs.expo.io/versions/latest/introduction/faq/#can-i-use-nodejs-packages-with-expo
Failed building JavaScript bundle.
---------------------
the cookie.js uses the line "var net = require('net');" . 
I am trying to run the code as a expo project. The net.js file in this repo is: 

exports.createServer =
exports.createConnection =
exports.connect =
function () {};

exports.isIP =
exports.isIPv4 =
exports.isIPv6 =
function () { return true };

-- 
Do I need to write this somewhere?

**Comment by parshap** [comment]
net is not included by default, there's two options:

## 1) Use the mock `net` implementation:

This doesn't actually provide any implementation, but makes it so if you require('net') you don't get an error:

```js
// rn-cli.config.js
module.exports = {
  resolver: {
    extraNodeModules: {
      ...require('node-libs-react-native'),
      net: require('node-libs-react-native/mock/net'),
    },
  },
};
```

## 2) Use react-native-tcp

This gives you an actual implementation of the net api: https://github.com/PeelTechnologies/react-native-tcp

Though it seems out of date at this point.

```js
// rn-cli.config.js
module.exports = {
  resolver: {
    extraNodeModules: {
      ...require('node-libs-react-native'),
      net: require('react-native-tcp'),
    },
  },
};
```

See https://github.com/parshap/node-libs-react-native#net

**Comment by SuryaChandrasekaran** [comment]
Thanks
