### ISSUE TITLE
No globals module.

### ISSUE THREAD

**Issue by zimmed** [parshap/node-libs-react-native#2]
Trying to figure out a separate issue where this package is not working in my react-native/expo-20.0.0 app due to `require.resolve` being undefined. In an attempt to fix, I followed the README and tried requiring the `node-libs-react-native/globals` in my globals file, but as it turns out, no such module exists.

Is it missing, or has it been deprecated without updating the README?

**Comment by parshap** [comment]
Nope, not deprecated. The `files` field was just left over from the original node-libs-browser fork. This should be fixed now and published in `1.0.2`. Thanks for reporting.
