### ISSUE TITLE
It doesn't work, what's the problem?

### ISSUE THREAD

**Issue by wonkyungup** [parshap/node-libs-react-native#35]
![스크린샷 2022-05-12 오후 11 04 17](https://user-images.githubusercontent.com/34180230/168093832-f9172a88-ccb9-4d37-a3c0-a68a177dda4a.png)
![스크린샷 2022-05-12 오후 11 04 28](https://user-images.githubusercontent.com/34180230/168093845-940b69d0-0661-4320-964d-fda58c315f8d.png)

I imported it to the root file index, and added metro.config.js > resolver > extraNodeModules require(), but there is a problem that it cannot be applied. Have I missed something?

**Comment by wonkyungup** [comment]
<img width="372" alt="스크린샷 2022-05-12 오후 11 07 41" src="https://user-images.githubusercontent.com/34180230/168094370-cef05aef-8980-4640-ab0e-bfca0160da67.png">

**Comment by yaszut** [comment]
Hi, 
have the same problem. how do you fix this?

**Comment by wonkyungup** [comment]
@yaszut  I did the processing using the rn-nodeify package.
https://www.npmjs.com/package/rn-nodeify
