### ISSUE TITLE
null is not an object (evaluating 'process.version.match ...)

### ISSUE THREAD

**Issue by akiradeveloper** [parshap/node-libs-react-native#8]
I am trying to use PlayFab's Node SDK from react-native and this library would help. I am testing with Android now.

After installing, the missing url and https modules are found but still one issue remains please help me.

The line of code that makes the error is https://github.com/PlayFab/NodeSDK/blob/master/PlayFabSdk/Scripts/PlayFab/PlayFab.js#L40 and it seeems process (or process.version) is null.

Do you know some workaround?

**Comment by parshap** [comment]
Are you including `node-libs-react-native/globals`? See the ["Globals"](https://github.com/parshap/node-libs-react-native#globals) section of the readme. This will shim `global.process` using the [process](https://github.com/defunctzombie/node-process) package which includes [setting `process.version` to an empty string](https://github.com/defunctzombie/node-process/blob/77caa43cdaee4ea710aa14d11cea1705293c0ef3/browser.js#L159), which should resolve your issue.

**Comment by akiradeveloper** [comment]
@parshap Yes. Without the include, there is an another error "Can't find variable: Buffer".

**Comment by akiradeveloper** [comment]
btw, if the process.version is empty string the match will fail and lead to out-of-bound error.

I found the error comes from this because the error is gone with this code.

```
require('node-libs-react-native/globals');
global.process.version = "v8.8";
```

The empty value form the node-process library needs overwriting in this case.

**Comment by parshap** [comment]
What's the error you're getting exactly?

Sounds like this library isn't really compatible with React Native because it depends on checking `process.version` and this is not really available in React Native. If you want to shim your own fake version of node in there, I think that's fine, but you might get some other unexpected consequences.

**Comment by akiradeveloper** [comment]
My code somehow works now with the fake Node.js version. So I want to close this issue for now and will open other issues when it is needed. Thanks for helping me out.
